### ISSUE TITLE
Installation instructions missing

### ISSUE THREAD

**Issue by yotammanor** [buzush/MapApp#1]
I have no idea how to install your project, and I'm tired of guessing.

Please describe the installation procedure, with different the OSs (Windows/Linux/Mac) in mind.

**Comment by noamoss** [comment]
just updated the readme.md 
What was the problem?

**Comment by yotammanor** [comment]
GeoSpatial libraries. Still not sure what exactly is needed in order for it to run.

https://docs.djangoproject.com/en/1.8/ref/contrib/gis/install/geolibs/

**Comment by noamoss** [comment]
Thanks. Please recheck and reply if it is clear enough.

**Comment by yotammanor** [comment]
Not sure what does it mean to install GDAL

**Comment by noamoss** [comment]
Nothing to be done. File updated, closing the issue.
